name: text2sql-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - fastapi>=0.115.0
      - uvicorn[standard]>=0.30.0
      - pydantic>=2.7
      - python-dotenv>=1.0.1
      - groq>=0.9.0
      - pytest>=8.0
      - pytest-cov>=5.0
      - httpx>=0.27
      - ruff>=0.5.0
